ENH: Transition to Python 3.10
Transition to Python 3.10.

Bump `scilpy` to eb5d3fb and upgrade dependencies accordingly.

Remove the dependencies force-upgrade in the package testing workflow,
as the versions required by `scilpy` are now modern enough to avoid the
primary issues they intended to fix.

Specifically, fix the BLAS option warning in `numpy` triggered by
`python-spams` when using an earlier version of `numpy`. Fixes:
```
AttributeError: module 'numpy.__config__' has no attribute 'blas_opt_info'

ERROR: Failed building wheel for python-spams
```

reported in:
https://github.com/scil-vital/tractolearn/actions/runs/4901866945/jobs/8753373506#step:5:945

Also, avoid using the `scilpy`-patched `dipy` version installation
issues reporting Cython is not being found by installing a more recent
version of `scilpy` using the commit hash. Fixes

```
RuntimeError: Need cython>=0.29.24 to build extensions but cannot import "Cython"
```

repored in
https://github.com/scil-vital/tractolearn/actions/runs/5384681010/jobs/9772886628#step:5:996