ENH: Modernize package setup
Modernize package setup.

Adopt PEP518 to specify minimum build system requirements for the
package using the `pyproject.toml` file.

Partially comply with PEP631:
- Dependencies are now stored in the `pyproject.toml` file, including
  packages that are not in PyPI (e.g. source code URLs -GitHub, etc.),
  so the related requirements files are removed.
- Wildcards are not accepted when specifying version values for the
  dependencies in the `pyproject.toml` file, as they need to be PEP
  508-compliant. Add a patch version or leave the minor version the
  where applicable.
- The script `setup.py` is no longer necessary: `pyproject.toml`
  contains the necessary information for the package set up.
- Project-specific `info.py` and `setup_helpers.py` scripts are no
  longer necessary.
- Describing the `flake8` configuration in the `pyproject.toml` is not
  yet supported, so it is kept in the `setup.cfg` file.

Add `torch` as a dependency and remove unnecessary dependencies:
`Cython`, `holoviews`, `pillow`, `plotly`, `scikit-image`, `vtk`,
`xlrd`, `xlsxwriter`.

Keep the development status to `Alpha`.

Adapt the GitHub Actions workflow file accordingly. Specifically,
- Set the `SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL` environment
  variable to `True` as some dependency is listing `scikit-learn` as
  `sklearn` in its dependencies. Àvoids:
  ```
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
      rather than 'sklearn' for pip commands.
  ```
  Documentation:
  https://github.com/scikit-learn/sklearn-pypi-package
- Comment testing as the package has not tests currently. Avoids:
  ```
  collecting ... collected 0 items
  Error: Process completed with exit code 5.
  ```

Adapt the documentation configuration script to read the necessary
project information from the `pyproject.toml` file.