ENH: Require `sphinx < 7.0.0` due to incompatibilities with `rtd-theme`
Require `sphinx < 7.0.0` due to incompatibilities with `rtd-theme`.

Fixes:
```
sphinx.errors.ThemeError: An error happened in rendering the page devel/coding_style_guideline.
Reason: UndefinedError("'style' is undefined")

Theme error:
An error happened in rendering the page devel/coding_style_guideline.
Reason: UndefinedError("'style' is undefined")
```

reported in:
https://readthedocs.org/projects/tractolearn/builds/21177008/

Documentation/evidence:
https://github.com/readthedocs/sphinx_rtd_theme/blob/1.2.2/setup.cfg#L48