BUG: Fix uses of `LoggerKeys` enum class entries
Fix uses of `LoggerKeys` enum class entries: use the intended `value`
property consistently.

Fixes:
```
Traceback (most recent call last):
  File "/tractolearn/scripts/ae_find_thresholds.py", line 497, in <module>
    main()
  File "/tractolearn/scripts/ae_find_thresholds.py", line 456, in main
    experiment_dir, LoggerKeys.latent_plot_fname_label + "_trk"
TypeError: unsupported operand type(s) for +: 'LoggerKeys' and 'str'
```

for those appearances where the corresponding enum entry was being used
without calling its `name` or `value` property.